### ISSUE TITLE
test_faulthandler failure 

### ISSUE THREAD

**Issue by jshelly** [vstinner/faulthandler#36]
CentOS 7.6, running Linux gl-build.arc-ts.umich.edu 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 on Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz.

Using gcc 8.2.0 compiled from source to build python 3.7.4 from source, `make test` fails with the following errors:

```
0:00:22 load avg: 3.12 [402/416/1] test_faulthandler failed
test test_faulthandler failed -- Traceback (most recent call last):
  File "/tmp/shellysw/build/Python-3.7.4/Lib/test/test_faulthandler.py", line 724, in test_register_chain
    self.check_register(chain=True)
  File "/tmp/shellysw/build/Python-3.7.4/Lib/test/test_faulthandler.py", line 702, in check_register
    self.assertEqual(exitcode, 0)
AssertionError: -11 != 0
```

I found a similar error reported in RedHat bugzilla (1687171) and tried running the script provided by Victor Stinner, and this closed issue on GitHub seems like it might be related?
https://github.com/vstinner/faulthandler/issues/32 because of the Skylake chipset.

Script:
```
import faulthandler, signal, os

def handler(signum, frame):
    handler.called = True
handler.called = False

faulthandler.enable()

signum = signal.SIGUSR1
signal.signal(signum, handler)
faulthandler.register(signum, chain=True)
os.kill(os.getpid(), signum)
print("called", handler.called)
```
It produced a segmentation fault.  I also ran that script using the python 3.6.6 binary that came installed with centos and it also produced a segmentation fault as well.

**Comment by vstinner** [comment]
Please open an issue at bugs.python.org. This is the backport to Python 2.7.

**Comment by vstinner** [comment]
Bug reported to https://bugs.python.org/issue37565
