### ISSUE TITLE
CPython merge #3929 needed

### ISSUE THREAD

**Issue by dee42** [vstinner/faulthandler#37]
I have a case of the Windows exception handler spamming a logfile until a machine runs out of space. This is because of missing the following commit: https://github.com/python/cpython/pull/3929/commits/2e4eee21301762c72d9f5b466ac49250b7a76bb3. The exception raised is one commonly used for debug logging, so you can connect a debugger and get logs from an object. What are the chances of this patch being ported to this faulthandler? I need to support older products still on Python 2.

**Comment by vstinner** [comment]
Would you mind to prepare a PR?

**Comment by vstinner** [comment]
I merged your PR and released faulthandler 3.2 which will be the last release of faulthandler backport. The 3.2 release also contains another fix for recent Intel CPUs.

> I need to support older products still on Python 2.

Or maybe I will release one more release if I'm paid for paid ;-)
